//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchEvents = new HashSet<MatchEvent>();
            this.MatchTeams = new HashSet<MatchTeam>();
        }
    
        public int MatchID { get; set; }
        public System.DateTime MatchDatetime { get; set; }
        public int LocationID { get; set; }
        public string OppositionName { get; set; }
        public int Duration { get; set; }
        public int Formation { get; set; }
        public string MatchNotes { get; set; }
        public string SelectedMatchType { get; set; }
        public int TeamID { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchEvent> MatchEvents { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchTeam> MatchTeams { get; set; }
    }
}
