//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamManager1Entities : DbContext
    {
        public TeamManager1Entities()
            : base("name=TeamManager1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MatchEvent> MatchEvents { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<MatchTeam> MatchTeams { get; set; }
        public virtual DbSet<PlayerRole> PlayerRoles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
